### PR TITLE
Find cand pos

### PR DESCRIPTION
**Pull request by NickSwainston**
Found a bug in the beamforming splicing when there is only a single beam, so I fixed that. 

Updated find_candidate_positon.nf, so it works with the new formatting.

Not sure why it shows 25 commits when only the last two are important after the merge.

### CODE REVIEW

**Comment by bwmeyers** [comment]
Apparently I completely missed this notification. I'm going to guess it's been tested on real data, etc.?

**Comment by NickSwainston** [comment]
Yup, I fixed it because I needed it to do some processing.

I assume it would be best to merge this after the other PR #8

**Comment by bwmeyers** [comment]
Why after? We can merge it into the dev branch and then that branch will be merged into master for deployment. Unless there's some specific reason you want to keep it back?

**Comment by NickSwainston** [comment]
Never mind, I thought my clean-up changes weren't merged. Not sure why it's showing the extra commits then.

**Comment by bwmeyers** [comment]
It's okay they'll all get squashed anyway when I merge this :)

**Pull request merged**
